// students.mjs
export const students = [
  { name: "Grace", cohort: "Inter", mark: 19 },
  { name: "Hank", cohort: "DDI", mark: 7 },
  { name: "Ivy", cohort: "Info", mark: 16 },
  { name: "Jack", cohort: "Miage", mark: 20 },
  { name: "Kara", cohort: "Info", mark: 5 },
  { name: "Leo", cohort: "Info", mark: 11 },
  { name: "Mia", cohort: "Info", mark: 17 },
  { name: "Nina", cohort: "DDD", mark: 6 },
  { name: "Oscar", cohort: "Info", mark: 13 },
  { name: "Paul", cohort: "DDI", mark: 9 },
  { name: "Quinn", cohort: "DDD", mark: 10 },
  { name: "Rita", cohort: "Info", mark: 11 },
  { name: "Sam", cohort: "DDI", mark: 12 },
  { name: "Tina", cohort: "Info", mark: 15 },
  { name: "Uma", cohort: "DDI", mark: 14 },
  { name: "Zane", cohort: "Info", mark: 9 },
  { name: "Brian", cohort: "DDD", mark: "ABJ" },
  { name: "Derek", cohort: "Info", mark: "ABJ" },
  { name: "Victor", cohort: "DDD", mark: 13 },
  { name: "Wendy", cohort: "Info", mark: 10 },
  { name: "Xander", cohort: "DDI", mark: 11 },
  { name: "Yara", cohort: "DDD", mark: 12 },
];